export const profile = {
  first_name: "Mushawiruddin",
  last_name: "Muhtar",
  bachelor_degree: "S.Kom",
  profession: "",
  city: "",
  state: "",
  address: "Bumi Taborong Permai L1/10",
  contact: [
    {
      twitter: "",
      linkedin: "",
      website: "",
      instagram: "",
      email: "angkomuhtar@gmail.com",
      phome: "+62 823-9305-0829",
    },
  ],
  work: [
    {
      id: 1,
      company: "CV. Avila Media Karya",
      location: "Makassar, Indonesia",
      time: "Mar 2020 - Oct 2021",
      job: "Frontend Developer",
      desc: [
        "Write modern, performant, maintainable code for a diverse array of client and internal projects",
        "Work with a variety of different languages, platforms, frameworks, and content management systems such as JavaScript, TypeScript, ReactJs, NextJs, Flutter, Redux",
      ],
      tech: ["ReactJs", "Tailwindcss", "Laravel"],
    },
    {
      id: 2,
      company: "PT. Telekomunikasi Seluler",
      location: "Makassar, Indonesia",
      time: "Dec 2019 - Mar 2021",
      job: "Admin Technical Support",
      desc: [
        "Collect and process Telkomsel provider customer data from the database into a report for the purpose of increasing sales",
        "Build and maintenance sales website for branch",
      ],
      tech: ["Apache Hadoop", "Bootstrap", "Laravel", "Mysql"],
    },
    {
      id: 3,
      company: "CV. Manre Nex Ekspresi",
      location: "Makassar, Indonesia",
      time: "Jun 2020 - Dec 2020",
      job: "React Native Developer",
      desc: ["Build a Online Food Reservation Mobile Apps Using React Native"],
      tech: ["React Native"],
    },
    {
      id: 4,
      company: "BKPSDM Jeneponto",
      location: "Makassar, Indonesia",
      time: "Apr 2018 - Sep 2019",
      job: "Fullstack Web Developer",
      desc: [
        "Build and maintain web monitoring and calculation of employee performance allowances within the government of Jeneponto ",
      ],
      tech: ["PHP", "HTML", "CSS", "Laravel", "Mysql", "Bootstrap"],
    },
    {
      id: 5,
      company: "PT. Amanah Bersama Ummat",
      location: "Makassar, Indonesia",
      time: "Mar 2016 - Aug 2017",
      job: "Fullstack Web Developer",
      desc: [
        "Build and monitoring website for intern company uses like a payroll, sales on branch, accounting, etc",
      ],
      tech: ["PHP", "HTML", "CSS", "Laravel", "Mysql", "Bootstrap"],
    },
  ],
};
